/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/airplane/son_5_gong.glb 
Author: StrykerDoesAnimation (https://sketchfab.com/strykerdoesgames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/goku-animation-34-c7069fade238468994333e9e1a93af19
Title: GOKU ANIMATION (3/4)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Son5Gong(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/airplane/son_5_gong.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  // 자동으로 첫 번째 애니메이션 클립 재생 (모델에 애니메이션이 포함되어 있다면)
  React.useEffect(() => {
    if (actions && Object.keys(actions).length > 0) {
      const clipName = Object.keys(actions)[0]
      actions[clipName].reset().play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, -0.5, Math.PI / 2]}>
          <group name="cc4a4a8fb446435994f79e3ce2f7e7dffbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_7" />
                  <group name="Object_9" />
                  <group name="Object_11" />
                  <group name="Object_13" />
                  <group name="Object_15" />
                  <group name="Object_17" />
                  <group name="Object_19" />
                  <group name="Object_21" />
                  <group name="Object_23" />
                  <group name="Object_26" />
                  <group name="RefRep259" />
                  <group name="RefRep261" />
                  <group name="RefRep263" />
                  <group name="RefRep265" />
                  <group name="RefRep267" />
                  <group name="RefRep269" />
                  <group name="RefRep271" />
                  <group name="RefRep273" />
                  <group name="RefRep275" />
                  <group name="RefRep277" />
                  <group name="RefRep279" />
                  <group name="RefRep281" />
                  <group name="RefRep283" />
                  <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.RootNode} skeleton={nodes.Object_6.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.RootNode} skeleton={nodes.Object_8.skeleton} />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.RootNode} skeleton={nodes.Object_10.skeleton} />
                  <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.RootNode} skeleton={nodes.Object_12.skeleton} />
                  <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.RootNode} skeleton={nodes.Object_14.skeleton} />
                  <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.RootNode} skeleton={nodes.Object_16.skeleton} />
                  <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.RootNode} skeleton={nodes.Object_18.skeleton} />
                  <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.RootNode} skeleton={nodes.Object_20.skeleton} />
                  <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.RootNode} skeleton={nodes.Object_22.skeleton} />
                  <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.RootNode} skeleton={nodes.Object_24.skeleton} />
                  <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.RootNode} skeleton={nodes.Object_25.skeleton} />
                  <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.RootNode} skeleton={nodes.Object_27.skeleton} />
                  <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.RootNode} skeleton={nodes.Object_28.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/airplane/son_5_gong.glb')

